# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'autoservice.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 400)
        MainWindow.setMinimumSize(QtCore.QSize(400, 400))
        MainWindow.setMaximumSize(QtCore.QSize(400, 400))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label_auto_service = QtWidgets.QLabel(self.centralwidget)
        self.label_auto_service.setGeometry(QtCore.QRect(109, 20, 151, 21))
        self.label_auto_service.setMaximumSize(QtCore.QSize(16777215, 16777202))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.label_auto_service.setFont(font)
        self.label_auto_service.setAlignment(QtCore.Qt.AlignCenter)
        self.label_auto_service.setObjectName("label_auto_service")
        self.input_service1 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_service1.setGeometry(QtCore.QRect(100, 160, 51, 21))
        self.input_service1.setObjectName("input_service1")
        self.input_service2 = QtWidgets.QLineEdit(self.centralwidget)
        self.input_service2.setGeometry(QtCore.QRect(260, 160, 71, 21))
        self.input_service2.setObjectName("input_service2")
        self.label_service1 = QtWidgets.QLabel(self.centralwidget)
        self.label_service1.setGeometry(QtCore.QRect(20, 160, 60, 16))
        self.label_service1.setObjectName("label_service1")
        self.label_service2 = QtWidgets.QLabel(self.centralwidget)
        self.label_service2.setGeometry(QtCore.QRect(180, 160, 60, 16))
        self.label_service2.setObjectName("label_service2")
        self.text_options = QtWidgets.QTextEdit(self.centralwidget)
        self.text_options.setGeometry(QtCore.QRect(73, 60, 251, 79))
        self.text_options.setObjectName("text_options")
        self.text_output = QtWidgets.QTextEdit(self.centralwidget)
        self.text_output.setGeometry(QtCore.QRect(50, 230, 301, 111))
        self.text_output.setObjectName("text_output")
        self.submit_button = QtWidgets.QPushButton(self.centralwidget)
        self.submit_button.setGeometry(QtCore.QRect(80, 190, 113, 32))
        self.submit_button.setObjectName("submit_button")
        self.clear_button = QtWidgets.QPushButton(self.centralwidget)
        self.clear_button.setGeometry(QtCore.QRect(210, 190, 113, 32))
        self.clear_button.setObjectName("clear_button")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 24))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_auto_service.setText(_translate("MainWindow", "Auto Service"))
        self.label_service1.setText(_translate("MainWindow", "Service 1"))
        self.label_service2.setText(_translate("MainWindow", "Service 2"))
        self.text_options.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">1. Oil change - $35</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">2. Tire rotation - $19</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">3. Car Wash - $7</p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">4. Car Wax - $12</p></body></html>"))
        self.text_output.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.AppleSystemUIFont\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please enter the number of the service being requested</p></body></html>"))
        self.submit_button.setText(_translate("MainWindow", "Submit"))
        self.clear_button.setText(_translate("MainWindow", "Clear"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
